services:
  - type: web
    name: kaiten-report-addon
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: KAITEN_API_TOKEN
        sync: false
      - key: KAITEN_CARD_ID
        sync: false
